<a href="https://colab.research.google.com/github/Juthathip-Saetan/Kaggle_Dataset_Titanic_V1/blob/main/Kaggle_Dataset_Titanic_V1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Kaggle-Titanic-Dataset---Machine-Learning-from-Disaster**

Predict survival on the Titanic and get familiar with ML basics

**The outline of our project**
+ Drop some unnecessary columns
+ Encode the data.

+ Train XGBoost model with GridSearchCV on training set

+ Train Random Forest model.

Download the dataset to the program.




In [ ]:
import pandas as pd
dataset = pd.read_csv('/content/train.csv')

In [ ]:
dataset.shape

(891, 12)

In [ ]:
dataset

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

Divide the dataset into X and y.

In [ ]:
X = dataset.drop(['Survived'],axis=1)

In [ ]:
X.shape

(891, 11)

In [ ]:
y = dataset['Survived']

In [ ]:
y.shape

(891,)

In [ ]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [ ]:
X

PassengerId  Pclass                                               Name  \
0              1       3                            Braund, Mr. Owen Harris   
1              2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2              3       3                             Heikkinen, Miss. Laina   
3              4       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4              5       3                           Allen, Mr. William Henry   
..           ...     ...                                                ...   
886          887       2                              Montvila, Rev. Juozas   
887          888       1                       Graham, Miss. Margaret Edith   
888          889       3           Johnston, Miss. Catherine Helen "Carrie"   
889          890       1                              Behr, Mr. Karl Howell   
890          891       3                                Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S  
1    female  38.0      1      0          PC 17599  71.2833   C85        C  
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
3    female  35.0      1      0            113803  53.1000  C123        S  
4      male  35.0      0      0            373450   8.0500   NaN        S  
..      ...   ...    ...    ...               ...      ...   ...      ...  
886    male  27.0      0      0            211536  13.0000   NaN        S  
887  female  19.0      0      0            112053  30.0000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889    male  26.0      0      0            111369  30.0000  C148        C  
890    male  32.0      0      0            370376   7.7500   NaN        Q  

[891 rows x 11 columns]

Split X and y to training and test set.

In [ ]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [ ]:
X_train.shape

(712, 11)

In [ ]:
X_test.shape

(179, 11)

In [ ]:
y_train.shape

(712,)

In [ ]:
y_test.shape

(179,)

Look at some information of the training set and check null values.



In [ ]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 28 to 484
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  712 non-null    int64  
 1   Pclass       712 non-null    int64  
 2   Name         712 non-null    object 
 3   Sex          712 non-null    object 
 4   Age          574 non-null    float64
 5   SibSp        712 non-null    int64  
 6   Parch        712 non-null    int64  
 7   Ticket       712 non-null    object 
 8   Fare         712 non-null    float64
 9   Cabin        163 non-null    object 
 10  Embarked     710 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 66.8+ KB


In [ ]:
X_train.head()

PassengerId  Pclass                               Name     Sex   Age  \
28            29       3      O'Dwyer, Miss. Ellen "Nellie"  female   NaN   
828          829       3       McCormack, Mr. Thomas Joseph    male   NaN   
275          276       1  Andrews, Miss. Kornelia Theodosia  female  63.0   
174          175       1            Smith, Mr. James Clinch    male  56.0   
120          121       2        Hickman, Mr. Stanley George    male  21.0   

     SibSp  Parch        Ticket     Fare Cabin Embarked  
28       0      0        330959   7.8792   NaN        Q  
828      0      0        367228   7.7500   NaN        Q  
275      1      0         13502  77.9583    D7        S  
174      0      0         17764  30.6958    A7        C  
120      2      0  S.O.C. 14879  73.5000   NaN        S

Drop some columns that we think they are unnecessary.


In [ ]:
X_train = X_train.drop(['PassengerId', 'Name', 'Age','Ticket','Cabin', 'Embarked'], axis=1)

In [ ]:
X_train.head()

Pclass     Sex  SibSp  Parch     Fare
28        3  female      0      0   7.8792
828       3    male      0      0   7.7500
275       1  female      1      0  77.9583
174       1    male      0      0  30.6958
120       2    male      2      0  73.5000

In [ ]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 28 to 484
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Pclass  712 non-null    int64  
 1   Sex     712 non-null    object 
 2   SibSp   712 non-null    int64  
 3   Parch   712 non-null    int64  
 4   Fare    712 non-null    float64
dtypes: float64(1), int64(3), object(1)
memory usage: 33.4+ KB


Encode the data.

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
label_enc_x = LabelEncoder()

In [ ]:
label_enc_x.fit(X_train['Sex'])

LabelEncoder()

In [ ]:
label_enc_x.classes_

array(['female', 'male'], dtype=object)

In [ ]:
label_enc_x.transform(X_train['Sex'])

array([0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,

In [ ]:
X_train 

Pclass     Sex  SibSp  Parch     Fare
28        3  female      0      0   7.8792
828       3    male      0      0   7.7500
275       1  female      1      0  77.9583
174       1    male      0      0  30.6958
120       2    male      2      0  73.5000
..      ...     ...    ...    ...      ...
374       3  female      3      1  21.0750
738       3    male      0      0   7.8958
63        3    male      3      2  27.9000
442       3    male      1      0   7.7750
484       1    male      1      0  91.0792

[712 rows x 5 columns]

In [ ]:
X_train['Sex'] = label_enc_x.transform(X_train['Sex'])

In [ ]:
X_train

Pclass  Sex  SibSp  Parch     Fare
28        3    0      0      0   7.8792
828       3    1      0      0   7.7500
275       1    0      1      0  77.9583
174       1    1      0      0  30.6958
120       2    1      2      0  73.5000
..      ...  ...    ...    ...      ...
374       3    0      3      1  21.0750
738       3    1      0      0   7.8958
63        3    1      3      2  27.9000
442       3    1      1      0   7.7750
484       1    1      1      0  91.0792

[712 rows x 5 columns]

Create the XGBoost model and to do the gridsearch option to find the best parameter settings.

In [ ]:
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV

xgb = XGBClassifier(
    objective='binary:logistic',
    nthread=4,
    seed=42
)

params_xgb = {
    'max_depth' : range(2, 10, 1),
    'n_estimators': range(100, 210, 10),
    'learning_rate': [0.1,0.01,0.05]
}

gs_xgb = GridSearchCV(estimator=xgb, param_grid=params_xgb, cv=5, verbose=3, scoring='accuracy')

Train the model with training data.

In [ ]:
gs_xgb.fit(X_train, y_train)

Fitting 5 folds for each of 264 candidates, totalling 1320 fits
[CV 1/5] END learning_rate=0.1, max_depth=2, n_estimators=100;, score=0.790 total time=   0.2s
[CV 2/5] END learning_rate=0.1, max_depth=2, n_estimators=100;, score=0.832 total time=   0.1s
[CV 3/5] END learning_rate=0.1, max_depth=2, n_estimators=100;, score=0.796 total time=   0.1s
[CV 4/5] END learning_rate=0.1, max_depth=2, n_estimators=100;, score=0.817 total time=   0.1s
[CV 5/5] END learning_rate=0.1, max_depth=2, n_estimators=100;, score=0.810 total time=   0.1s
[CV 1/5] END learning_rate=0.1, max_depth=2, n_estimators=110;, score=0.797 total time=   0.1s
[CV 2/5] END learning_rate=0.1, max_depth=2, n_estimators=110;, score=0.825 total time=   0.1s
[CV 3/5] END learning_rate=0.1, max_depth=2, n_estimators=110;, score=0.796 total time=   0.2s
[CV 4/5] END learning_rate=0.1, max_depth=2, n_estimators=110;, score=0.817 total time=   0.2s
[CV 5/5] END learning_rate=0.1, max_depth=2, n_estimators=110;, score=0.810 total

GridSearchCV(cv=5, estimator=XGBClassifier(nthread=4, seed=42),
             param_grid={'learning_rate': [0.1, 0.01, 0.05],
                         'max_depth': range(2, 10),
                         'n_estimators': range(100, 210, 10)},
             scoring='accuracy', verbose=3)

Look at the best parameter setting and its score (accuracy).

In [ ]:
gs_xgb.best_score_

0.8272628779671033

In [ ]:
gs_xgb.best_params_

{'learning_rate': 0.05, 'max_depth': 7, 'n_estimators': 100}

Check the score on training data.

In [ ]:
from sklearn.metrics import accuracy_score 
accuracy_score(y_train,gs_xgb.predict(X_train))

0.8834269662921348

Let's evaluate the test data but we need to do some feature engineering steps. the same process as we do on the training data.

In [ ]:
X_test = X_test.drop(['PassengerId', 'Name', 'Age','Ticket','Cabin','Embarked'],axis=1)

In [ ]:
X_test['Sex'] = label_enc_x.transform(X_test['Sex'])

In [ ]:
X_test

Pclass  Sex  SibSp  Parch      Fare
481       2    1      0      0    0.0000
651       2    0      0      1   23.0000
164       3    1      4      1   39.6875
838       3    1      0      0   56.4958
251       3    0      1      1   10.4625
..      ...  ...    ...    ...       ...
146       3    1      0      0    7.7958
211       2    0      0      0   21.0000
130       3    1      0      0    7.8958
550       1    1      0      2  110.8833
354       3    1      0      0    7.2250

[179 rows x 5 columns]

In [ ]:
gs_xgb.predict(X_test)

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0])

Check the score on test data.

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
y_predict = gs_xgb.predict(X_test)

In [ ]:
accuracy_score(y_test, y_predict )

0.7988826815642458

Let''s load the kaggle test data (without target y).

In [ ]:
X_realworld = pd.read_csv('/content/test.csv')

In [ ]:
X_realworld.shape

(418, 11)

In [ ]:
X_realworld

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

Do the feature engineering steps to the kaggle test data.

In [ ]:
X_realworld = X_realworld.drop(['PassengerId','Name','Age','Ticket','Cabin','Embarked'], axis=1)

In [ ]:
X_realworld.head()

Pclass     Sex  SibSp  Parch     Fare
0       3    male      0      0   7.8292
1       3  female      1      0   7.0000
2       2    male      0      0   9.6875
3       3    male      0      0   8.6625
4       3  female      1      1  12.2875

In [ ]:
X_realworld['Sex'] = label_enc_x.transform(X_realworld['Sex'])

In [ ]:
X_realworld

Pclass  Sex  SibSp  Parch      Fare
0         3    1      0      0    7.8292
1         3    0      1      0    7.0000
2         2    1      0      0    9.6875
3         3    1      0      0    8.6625
4         3    0      1      1   12.2875
..      ...  ...    ...    ...       ...
413       3    1      0      0    8.0500
414       1    0      0      0  108.9000
415       3    1      0      0    7.2500
416       3    1      0      0    8.0500
417       3    1      1      1   22.3583

[418 rows x 5 columns]

Lest's predict the kaggle data.

In [ ]:
gs_xgb.predict(X_realworld)

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

Load the submisssion file to create our own prediction file (using our model).

In [ ]:
gender_submission = pd.read_csv('/content/gender_submission.csv')

In [ ]:
import numpy as np

In [ ]:
np.array(gender_submission['Survived']) == gs_xgb.predict(X_realworld)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True, False, False,  True,
       False, False,  True, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [ ]:
np.array(gender_submission['Survived'])

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [ ]:
gender_submission['Survived'] = gs_xgb.predict(X_realworld)

In [ ]:
gender_submission

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

Save the excel file, then finished.

In [ ]:
gender_submission.to_csv('/content/GridSearch_XGBoost_submission.csv',index=False)

Train Random Forest model.

In [ ]:
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier(n_estimators=100,max_depth=6,random_state=5)
random_forest.fit(X_train, y_train)

RandomForestClassifier(max_depth=6, random_state=5)

In [ ]:
random_forest.score(X_train, y_train)

0.8707865168539326

In [ ]:
Y_pred1 = random_forest.predict(X_test)

In [ ]:
accuracy_score(y_test,Y_pred1)

0.7988826815642458

In [ ]:
X_realworld.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Pclass  418 non-null    int64  
 1   Sex     418 non-null    int64  
 2   SibSp   418 non-null    int64  
 3   Parch   418 non-null    int64  
 4   Fare    417 non-null    float64
dtypes: float64(1), int64(4)
memory usage: 16.5 KB


In [ ]:
from sklearn.impute  import SimpleImputer
import numpy as np

imp_median = SimpleImputer(missing_values=np.nan, strategy='median')

In [ ]:
float64_columns = ['Fare']

In [ ]:
imp_median.fit(X_realworld[float64_columns])

SimpleImputer(strategy='median')

In [ ]:
X_realworld[float64_columns] = imp_median.transform(X_realworld[float64_columns])

In [ ]:
X_realworld.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Pclass  418 non-null    int64  
 1   Sex     418 non-null    int64  
 2   SibSp   418 non-null    int64  
 3   Parch   418 non-null    int64  
 4   Fare    418 non-null    float64
dtypes: float64(1), int64(4)
memory usage: 16.5 KB


In [ ]:
random_forest.predict(X_realworld)

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [ ]:
random_forest_submission = gender_submission.copy()

In [ ]:
random_forest_submission['Survived'] = random_forest.predict(X_realworld)
random_forest_submission

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [ ]:
random_forest_submission.to_csv('/content/Random_forest_submission.csv',index=False)